# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-31 05:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_auto_20170828_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thing',
            name='user',
        ),
        migrations.DeleteModel(
            name='Thing',
        ),
    ]
