# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0007_auto_20170901_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='public',
            field=models.CharField(choices=[('PRIVATE', 'only me'), ('PUBLIC', 'everyone')], default='PRIVATE', max_length=7),
        ),
    ]
